apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  type: NodePort
  ports:
    - name: docker-port
      port: 80
      targetPort: 80
      nodeport: 30007
